<a href="https://colab.research.google.com/github/piyu18/Learn_TensorFlow/blob/main/tensorflow_Day01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## What is TensorFlow?
[Tensorflow](https://www.tensorflow.org/) is an open-source end-to-end machine learning library for preprocessing data, modelling data and serving models.
Rather than building machine learning and deep learning models from scratch, it's more likely we'll use a library such as TensorFlow. This is because it contains many of the most common machine learning functions we want to use.

## Introduction to Tensor

In [2]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.9.2


In [3]:
# Create tensors with tf.constant()
scalar = tf.constant(13)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=13>

In [4]:
# Check the no of dimensions of a tensor(ndim)
scalar.ndim

0

In [5]:
# Create a vector
vector = tf.constant([2,3])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [6]:
vector.ndim

1

In [7]:
# Create a matrix(more than one dimension)
matrix = tf.constant([[2,3,4],
                      [4,2,3]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [4, 2, 3]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
from numpy import float16
# Create another matrix
matrix1 = tf.constant([[2.,3.],
                       [3.,7.],
                       [7.,8.]], dtype=float16)
matrix1

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[2., 3.],
       [3., 7.],
       [7., 8.]], dtype=float16)>

In [10]:
matrix1.ndim

2

In [11]:
# Create a tensor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [12]:
tensor.ndim

3

## Creating tensors with tf.Variable

In [13]:
# Create tensor with tf.Variable()
tensor1 = tf.Variable([10,7])
tensor1_constant = tf.constant([10,7])
tensor1, tensor1_constant

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
# Let's try to change the value of tensor1
tensor1[0] = 7

TypeError: ignored

In [15]:
# Let's try with .assign()
tensor1[0].assign(7)
tensor1

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [16]:
# Let's try to change the value of tensor1_constant
#tensor1_constant[0] = 7
tensor1_constant[0].assign(7)
# There might be cases where we don't want our tensor value to get change, in that case we will use tf.constant()

AttributeError: ignored

### Creating random tensors

In [17]:
# Outputs random values from a normal distribution.
random1 = tf.random.Generator.from_seed(42)
random1 = random1.normal(shape=(3,2))
random1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [18]:
# Outputs random values from a uniform distribution.
random2 = tf.random.Generator.from_seed(7)
random2 = random2.uniform(shape=(3,2),minval=1,maxval=2)
random2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1.3993284, 1.7840713],
       [1.6788015, 1.733959 ],
       [1.5520444, 1.1094851]], dtype=float32)>

### Shuffle a tensor
Randomly shuffles a tensor along its first dimension.
tf.random.shuffle

In [19]:
not_shuffled = tf.constant([[2,3],
                            [5,7],
                            [11,13]])
# Shuffle the not_shuffled data
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 13],
       [ 5,  7],
       [ 2,  3]], dtype=int32)>

In [20]:
tf.random.shuffle(not_shuffled,seed=7)#operation level seed
# In this case we don't see the actual affect of seed, as global seed is not set.

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  3],
       [11, 13],
       [ 5,  7]], dtype=int32)>

https://www.tensorflow.org/api_docs/python/tf/random/set_seed
> Rule 4: "Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds."

In [21]:
tf.random.set_seed(23) # global level operation seed
tf.random.shuffle(not_shuffled,seed=7)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5,  7],
       [11, 13],
       [ 2,  3]], dtype=int32)>

In [22]:
# Create a tensor of all ones
tf.ones([5,5])

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [23]:
# Create a tensor of all zeros
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

###  Numpy arrays to tensors
The main difference between Numpy arrays and TensorFlow tensors is that tensor are supported by accelerated memory such as GPU. 


In [24]:
import numpy as np
numpy_A = np.arange(1,25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [25]:
tf_numpy_A = tf.constant(numpy_A,shape=(6,2,2))
tf_numpy_A1 = tf.constant(numpy_A)
tf_numpy_A, tf_numpy_A1

(<tf.Tensor: shape=(6, 2, 2), dtype=int32, numpy=
 array([[[ 1,  2],
         [ 3,  4]],
 
        [[ 5,  6],
         [ 7,  8]],
 
        [[ 9, 10],
         [11, 12]],
 
        [[13, 14],
         [15, 16]],
 
        [[17, 18],
         [19, 20]],
 
        [[21, 22],
         [23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [26]:
tf_numpy_A.ndim

3

In [27]:
tf_numpy_A1.ndim

1

### Getting tensor's information
* Shape
* Rank
* Axis or dimension
* Size

In [31]:
# Create a rank 5 tensor (5 dimensions)
rank_5_tensor = tf.zeros(shape=(1,2,3,4,5))
rank_5_tensor

<tf.Tensor: shape=(1, 2, 3, 4, 5), dtype=float32, numpy=
array([[[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]]]], dtype=float32)>

In [36]:
rank_5_tensor[0]

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [37]:
rank_5_tensor.shape, rank_5_tensor.ndim, tf.size(rank_5_tensor)

(TensorShape([1, 2, 3, 4, 5]),
 5,
 <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [41]:
print('Elements along 0 axis:',rank_5_tensor.shape[0])
print('Elements along last axis:',rank_5_tensor.shape[-1])
print('Total no of elements in tensor:',tf.size(rank_5_tensor))
print('Total no of elements in tensor:',tf.size(rank_5_tensor).numpy())

Elements along 0 axis: 1
Elements along last axis: 5
Total no of elements in tensor: tf.Tensor(120, shape=(), dtype=int32)
Total no of elements in tensor: 120


### Indexing in tensor


In [42]:
rank_5_tensor[:2,:2,:2,:2,:2]

<tf.Tensor: shape=(1, 2, 2, 2, 2), dtype=float32, numpy=
array([[[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]]], dtype=float32)>

In [49]:
# Get the first element from each dimension except last
rank_5_tensor[:1,:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 1, 5), dtype=float32, numpy=array([[[[[0., 0., 0., 0., 0.]]]]], dtype=float32)>

In [66]:
rank_5_tensor[:1,:1,:2:,:3,:3]

<tf.Tensor: shape=(1, 1, 2, 3, 3), dtype=float32, numpy=
array([[[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]]], dtype=float32)>

In [67]:
# Create a rank 3 tensor (3 dimensions)
rank_3_tensor = tf.constant([[[1,2,3],
                             [4,5,6],
                              [7,8,9]]])
rank_3_tensor.shape, rank_3_tensor.ndim

(TensorShape([1, 3, 3]), 3)

In [72]:
# Getting the last element of each row
rank_3_tensor[:,:,-1]

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[3, 6, 9]], dtype=int32)>

In [74]:
# Getting the first element of each row
rank_3_tensor[:,:,0]

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 4, 7]], dtype=int32)>

In [82]:
rank_3_tensor[:,-1,]

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[7, 8, 9]], dtype=int32)>

In [84]:
# Add in extra dimension 
rank_4_tensor = rank_3_tensor[..., tf.newaxis] #Instead of writing like [:,:,:] we can write [...], add extra dimension in the end
rank_4_tensor

<tf.Tensor: shape=(1, 3, 3, 1), dtype=int32, numpy=
array([[[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]],

        [[7],
         [8],
         [9]]]], dtype=int32)>

In [85]:
# Alternative to tf.newaxis
tf.expand_dims(rank_3_tensor,axis=-1)

<tf.Tensor: shape=(1, 3, 3, 1), dtype=int32, numpy=
array([[[[1],
         [2],
         [3]],

        [[4],
         [5],
         [6]],

        [[7],
         [8],
         [9]]]], dtype=int32)>

In [90]:
tf.expand_dims(rank_3_tensor,axis=2)

<tf.Tensor: shape=(1, 3, 1, 3), dtype=int32, numpy=
array([[[[1, 2, 3]],

        [[4, 5, 6]],

        [[7, 8, 9]]]], dtype=int32)>