<a href="https://colab.research.google.com/github/piyu18/Learn_TensorFlow/blob/main/TensorFlow_Day02_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import TensorFlow
import tensorflow as tf

### Variance and Standard Deviation in TensorFlow
  * `tf.math.reduce_std()` -> Computes the standard deviation of elements across dimensions of a tensor.
  * `tfp.stats.variance()` -> Estimates the variance



In [2]:
# Create a tensor with 30 random values between 0 and 100
import numpy as np
X1 = tf.constant(np.random.randint(low=0, high=110, size=30))
X1

<tf.Tensor: shape=(30,), dtype=int64, numpy=
array([  4,  62,  79,  42,  85,  35,  61,  61,  38,  20,  37, 100,  35,
        41,   6,   8,  28,  73,  39, 106,  46,  74, 100,   8,  66, 107,
        34,  21,  38,  24])>

In [3]:
# Calculate Variance
import tensorflow_probability as tfp
tfp.stats.variance(X1)

<tf.Tensor: shape=(), dtype=int64, numpy=903>

In [4]:
# Calculate Std deviation
tf.math.reduce_std(X1)

TypeError: ignored

As we can see that `tf.math.reduce_std()` only accepts real and complex no, so we have to change the type of our data

In [5]:
# Convert int64 to float32
tf.math.reduce_std(tf.cast(X1, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=30.059866>

### TensorFlow Squeeze
`tf.squeeze()` -> Removes dimensions of size 1 from the shape of a tensor.

In [6]:
# Create a tensor
X2 = tf.constant(tf.random.uniform(shape=[20]),shape=[1,1,1,20])
X2

<tf.Tensor: shape=(1, 1, 1, 20), dtype=float32, numpy=
array([[[[0.5532799 , 0.5576147 , 0.10667801, 0.49840486, 0.14909327,
          0.35542428, 0.2944758 , 0.07129622, 0.44076645, 0.3718586 ,
          0.94122875, 0.80234647, 0.0070231 , 0.38027966, 0.7272756 ,
          0.96195483, 0.99689555, 0.67693746, 0.7685406 , 0.08358443]]]],
      dtype=float32)>

In [7]:
# Squeeze the tensor
tf.squeeze(X2)

<tf.Tensor: shape=(20,), dtype=float32, numpy=
array([0.5532799 , 0.5576147 , 0.10667801, 0.49840486, 0.14909327,
       0.35542428, 0.2944758 , 0.07129622, 0.44076645, 0.3718586 ,
       0.94122875, 0.80234647, 0.0070231 , 0.38027966, 0.7272756 ,
       0.96195483, 0.99689555, 0.67693746, 0.7685406 , 0.08358443],
      dtype=float32)>

In [8]:
X3 = tf.constant(tf.random.uniform(shape=[50],minval=10, maxval=100, dtype=tf.int32), shape=[1,1,1,2,25])
X3

<tf.Tensor: shape=(1, 1, 1, 2, 25), dtype=int32, numpy=
array([[[[[15, 54, 67, 13, 73, 29, 85, 58, 37, 22, 82, 14, 82, 66, 29,
           55, 84, 82, 45, 63, 93, 15, 25, 62, 80],
          [88, 85, 15, 60, 49, 29, 64, 80, 39, 61, 95, 75, 49, 87, 55,
           33, 52, 78, 92, 89, 10, 96, 29, 68, 13]]]]], dtype=int32)>

In [9]:
tf.squeeze(X3)

<tf.Tensor: shape=(2, 25), dtype=int32, numpy=
array([[15, 54, 67, 13, 73, 29, 85, 58, 37, 22, 82, 14, 82, 66, 29, 55,
        84, 82, 45, 63, 93, 15, 25, 62, 80],
       [88, 85, 15, 60, 49, 29, 64, 80, 39, 61, 95, 75, 49, 87, 55, 33,
        52, 78, 92, 89, 10, 96, 29, 68, 13]], dtype=int32)>

In [10]:
X4 = tf.constant(tf.random.uniform(shape=[20],minval=10, maxval=100, dtype=tf.int32), shape=[1,1,1,1,2,10])
X4

<tf.Tensor: shape=(1, 1, 1, 1, 2, 10), dtype=int32, numpy=
array([[[[[[66, 73, 59, 73, 95, 91, 43, 93, 99, 20],
           [64, 10, 84, 82, 94, 35, 12, 91, 21, 91]]]]]], dtype=int32)>

In [11]:
tf.squeeze(X4, [1,3]) 

<tf.Tensor: shape=(1, 1, 2, 10), dtype=int32, numpy=
array([[[[66, 73, 59, 73, 95, 91, 43, 93, 99, 20],
         [64, 10, 84, 82, 94, 35, 12, 91, 21, 91]]]], dtype=int32)>