<a href="https://colab.research.google.com/github/piyu18/Learn_TensorFlow/blob/main/TensorFlow_Day02_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import TensorFlow
import tensorflow as tf

### Variance and Standard Deviation in TensorFlow
  * `tf.math.reduce_std()` -> Computes the standard deviation of elements across dimensions of a tensor.
  * `tfp.stats.variance()` -> Estimates the variance



In [2]:
# Create a tensor with 30 random values between 0 and 100
import numpy as np
X1 = tf.constant(np.random.randint(low=0, high=110, size=30))
X1

<tf.Tensor: shape=(30,), dtype=int64, numpy=
array([ 66,  60,  82,  50,  62,  80,  98,  65,  62, 106, 104,  24,   1,
        78,  98,  90,  63,  31,  14,   2,  97,  59,  20,  76,  60,  51,
       100,  73,  66,  11])>

In [3]:
# Calculate Variance
import tensorflow_probability as tfp
tfp.stats.variance(X1)

<tf.Tensor: shape=(), dtype=int64, numpy=925>

In [4]:
# Calculate Std deviation
tf.math.reduce_std(X1)

TypeError: ignored

As we can see that `tf.math.reduce_std()` only accepts real and complex no, so we have to change the type of our data

In [5]:
# Convert int64 to float32
tf.math.reduce_std(tf.cast(X1, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=30.417631>

### TensorFlow Squeeze
`tf.squeeze()` -> Removes dimensions of size 1 from the shape of a tensor.

In [6]:
# Create a tensor
X2 = tf.constant(tf.random.uniform(shape=[20]),shape=[1,1,1,20])
X2

<tf.Tensor: shape=(1, 1, 1, 20), dtype=float32, numpy=
array([[[[0.2944181 , 0.07496345, 0.75908756, 0.37098694, 0.0229733 ,
          0.6194639 , 0.9213797 , 0.09461701, 0.37774038, 0.7560067 ,
          0.12451136, 0.33121395, 0.03219354, 0.8136115 , 0.9464791 ,
          0.28960526, 0.09681916, 0.20769823, 0.21366143, 0.73628056]]]],
      dtype=float32)>

In [7]:
# Squeeze the tensor
tf.squeeze(X2)

<tf.Tensor: shape=(20,), dtype=float32, numpy=
array([0.2944181 , 0.07496345, 0.75908756, 0.37098694, 0.0229733 ,
       0.6194639 , 0.9213797 , 0.09461701, 0.37774038, 0.7560067 ,
       0.12451136, 0.33121395, 0.03219354, 0.8136115 , 0.9464791 ,
       0.28960526, 0.09681916, 0.20769823, 0.21366143, 0.73628056],
      dtype=float32)>

In [8]:
X3 = tf.constant(tf.random.uniform(shape=[50],minval=10, maxval=100, dtype=tf.int32), shape=[1,1,1,2,25])
X3

<tf.Tensor: shape=(1, 1, 1, 2, 25), dtype=int32, numpy=
array([[[[[40, 24, 17, 92, 21, 80, 13, 56, 88, 31, 88, 16, 35, 69, 19,
           31, 89, 86, 62, 21, 28, 98, 51, 88, 21],
          [95, 83, 49, 51, 95, 62, 98, 30, 81, 18, 17, 64, 43, 22, 33,
           87, 69, 29, 13, 18, 62, 52, 10, 18, 72]]]]], dtype=int32)>

In [9]:
tf.squeeze(X3)

<tf.Tensor: shape=(2, 25), dtype=int32, numpy=
array([[40, 24, 17, 92, 21, 80, 13, 56, 88, 31, 88, 16, 35, 69, 19, 31,
        89, 86, 62, 21, 28, 98, 51, 88, 21],
       [95, 83, 49, 51, 95, 62, 98, 30, 81, 18, 17, 64, 43, 22, 33, 87,
        69, 29, 13, 18, 62, 52, 10, 18, 72]], dtype=int32)>

In [91]:
X4 = tf.constant(tf.random.uniform(shape=[20],minval=10, maxval=100, dtype=tf.int32), shape=[1,1,1,1,2,10])
X4

<tf.Tensor: shape=(1, 1, 1, 1, 2, 10), dtype=int32, numpy=
array([[[[[[72, 21, 90, 11, 77, 96, 11, 16, 72, 25],
           [20, 74, 68, 23, 65, 94, 43, 92, 81, 21]]]]]], dtype=int32)>

In [94]:
tf.squeeze(X4, [1,3]) 

<tf.Tensor: shape=(1, 1, 2, 10), dtype=int32, numpy=
array([[[[72, 21, 90, 11, 77, 96, 11, 16, 72, 25],
         [20, 74, 68, 23, 65, 94, 43, 92, 81, 21]]]], dtype=int32)>